################################################################################
# Automatically-generated file. Do not edit!
# Toolchain: GNU Tools for STM32 (13.3.rel1)
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
CC_SRCS += \
../Middlewares/TFLM/micro/kernels/activations.cc \
../Middlewares/TFLM/micro/kernels/activations_common.cc \
../Middlewares/TFLM/micro/kernels/activations_test.cc \
../Middlewares/TFLM/micro/kernels/add.cc \
../Middlewares/TFLM/micro/kernels/add_common.cc \
../Middlewares/TFLM/micro/kernels/add_n.cc \
../Middlewares/TFLM/micro/kernels/add_n_test.cc \
../Middlewares/TFLM/micro/kernels/add_test.cc \
../Middlewares/TFLM/micro/kernels/arg_min_max.cc \
../Middlewares/TFLM/micro/kernels/arg_min_max_test.cc \
../Middlewares/TFLM/micro/kernels/assign_variable.cc \
../Middlewares/TFLM/micro/kernels/batch_matmul.cc \
../Middlewares/TFLM/micro/kernels/batch_matmul_common.cc \
../Middlewares/TFLM/micro/kernels/batch_matmul_test.cc \
../Middlewares/TFLM/micro/kernels/batch_to_space_nd.cc \
../Middlewares/TFLM/micro/kernels/batch_to_space_nd_test.cc \
../Middlewares/TFLM/micro/kernels/broadcast_args.cc \
../Middlewares/TFLM/micro/kernels/broadcast_args_test.cc \
../Middlewares/TFLM/micro/kernels/broadcast_to.cc \
../Middlewares/TFLM/micro/kernels/broadcast_to_test.cc \
../Middlewares/TFLM/micro/kernels/call_once.cc \
../Middlewares/TFLM/micro/kernels/call_once_test.cc \
../Middlewares/TFLM/micro/kernels/cast.cc \
../Middlewares/TFLM/micro/kernels/cast_test.cc \
../Middlewares/TFLM/micro/kernels/ceil.cc \
../Middlewares/TFLM/micro/kernels/ceil_test.cc \
../Middlewares/TFLM/micro/kernels/circular_buffer.cc \
../Middlewares/TFLM/micro/kernels/circular_buffer_common.cc \
../Middlewares/TFLM/micro/kernels/circular_buffer_flexbuffers_generated_data.cc \
../Middlewares/TFLM/micro/kernels/circular_buffer_test.cc \
../Middlewares/TFLM/micro/kernels/comparisons.cc \
../Middlewares/TFLM/micro/kernels/comparisons_test.cc \
../Middlewares/TFLM/micro/kernels/concatenation.cc \
../Middlewares/TFLM/micro/kernels/concatenation_test.cc \
../Middlewares/TFLM/micro/kernels/conv.cc \
../Middlewares/TFLM/micro/kernels/conv_common.cc \
../Middlewares/TFLM/micro/kernels/conv_test.cc \
../Middlewares/TFLM/micro/kernels/conv_test_common.cc \
../Middlewares/TFLM/micro/kernels/cumsum.cc \
../Middlewares/TFLM/micro/kernels/cumsum_test.cc \
../Middlewares/TFLM/micro/kernels/decompress.cc \
../Middlewares/TFLM/micro/kernels/decompress_common.cc \
../Middlewares/TFLM/micro/kernels/decompress_test.cc \
../Middlewares/TFLM/micro/kernels/depth_to_space.cc \
../Middlewares/TFLM/micro/kernels/depth_to_space_test.cc \
../Middlewares/TFLM/micro/kernels/depthwise_conv.cc \
../Middlewares/TFLM/micro/kernels/depthwise_conv_common.cc \
../Middlewares/TFLM/micro/kernels/depthwise_conv_test.cc \
../Middlewares/TFLM/micro/kernels/dequantize.cc \
../Middlewares/TFLM/micro/kernels/dequantize_common.cc \
../Middlewares/TFLM/micro/kernels/dequantize_test.cc \
../Middlewares/TFLM/micro/kernels/detection_postprocess.cc \
../Middlewares/TFLM/micro/kernels/detection_postprocess_flexbuffers_generated_data.cc \
../Middlewares/TFLM/micro/kernels/detection_postprocess_test.cc \
../Middlewares/TFLM/micro/kernels/div.cc \
../Middlewares/TFLM/micro/kernels/div_test.cc \
../Middlewares/TFLM/micro/kernels/elementwise.cc \
../Middlewares/TFLM/micro/kernels/elementwise_test.cc \
../Middlewares/TFLM/micro/kernels/elu.cc \
../Middlewares/TFLM/micro/kernels/elu_test.cc \
../Middlewares/TFLM/micro/kernels/embedding_lookup.cc \
../Middlewares/TFLM/micro/kernels/embedding_lookup_test.cc \
../Middlewares/TFLM/micro/kernels/ethosu.cc \
../Middlewares/TFLM/micro/kernels/exp.cc \
../Middlewares/TFLM/micro/kernels/exp_test.cc \
../Middlewares/TFLM/micro/kernels/expand_dims.cc \
../Middlewares/TFLM/micro/kernels/expand_dims_test.cc \
../Middlewares/TFLM/micro/kernels/fill.cc \
../Middlewares/TFLM/micro/kernels/fill_test.cc \
../Middlewares/TFLM/micro/kernels/floor.cc \
../Middlewares/TFLM/micro/kernels/floor_div.cc \
../Middlewares/TFLM/micro/kernels/floor_div_test.cc \
../Middlewares/TFLM/micro/kernels/floor_mod.cc \
../Middlewares/TFLM/micro/kernels/floor_mod_test.cc \
../Middlewares/TFLM/micro/kernels/floor_test.cc \
../Middlewares/TFLM/micro/kernels/fully_connected.cc \
../Middlewares/TFLM/micro/kernels/fully_connected_common.cc \
../Middlewares/TFLM/micro/kernels/fully_connected_test.cc \
../Middlewares/TFLM/micro/kernels/gather.cc \
../Middlewares/TFLM/micro/kernels/gather_nd.cc \
../Middlewares/TFLM/micro/kernels/gather_nd_test.cc \
../Middlewares/TFLM/micro/kernels/gather_test.cc \
../Middlewares/TFLM/micro/kernels/hard_swish.cc \
../Middlewares/TFLM/micro/kernels/hard_swish_common.cc \
../Middlewares/TFLM/micro/kernels/hard_swish_test.cc \
../Middlewares/TFLM/micro/kernels/if.cc \
../Middlewares/TFLM/micro/kernels/if_test.cc \
../Middlewares/TFLM/micro/kernels/kernel_runner.cc \
../Middlewares/TFLM/micro/kernels/kernel_util.cc \
../Middlewares/TFLM/micro/kernels/l2_pool_2d.cc \
../Middlewares/TFLM/micro/kernels/l2_pool_2d_test.cc \
../Middlewares/TFLM/micro/kernels/l2norm.cc \
../Middlewares/TFLM/micro/kernels/l2norm_test.cc \
../Middlewares/TFLM/micro/kernels/leaky_relu.cc \
../Middlewares/TFLM/micro/kernels/leaky_relu_common.cc \
../Middlewares/TFLM/micro/kernels/leaky_relu_test.cc \
../Middlewares/TFLM/micro/kernels/log_softmax.cc \
../Middlewares/TFLM/micro/kernels/log_softmax_test.cc \
../Middlewares/TFLM/micro/kernels/logical.cc \
../Middlewares/TFLM/micro/kernels/logical_common.cc \
../Middlewares/TFLM/micro/kernels/logical_test.cc \
../Middlewares/TFLM/micro/kernels/logistic.cc \
../Middlewares/TFLM/micro/kernels/logistic_common.cc \
../Middlewares/TFLM/micro/kernels/logistic_test.cc \
../Middlewares/TFLM/micro/kernels/lstm_eval.cc \
../Middlewares/TFLM/micro/kernels/lstm_eval_common.cc \
../Middlewares/TFLM/micro/kernels/lstm_eval_test.cc \
../Middlewares/TFLM/micro/kernels/maximum_minimum.cc \
../Middlewares/TFLM/micro/kernels/maximum_minimum_test.cc \
../Middlewares/TFLM/micro/kernels/micro_tensor_utils.cc \
../Middlewares/TFLM/micro/kernels/mirror_pad.cc \
../Middlewares/TFLM/micro/kernels/mirror_pad_test.cc \
../Middlewares/TFLM/micro/kernels/mul.cc \
../Middlewares/TFLM/micro/kernels/mul_common.cc \
../Middlewares/TFLM/micro/kernels/mul_test.cc \
../Middlewares/TFLM/micro/kernels/neg.cc \
../Middlewares/TFLM/micro/kernels/neg_test.cc \
../Middlewares/TFLM/micro/kernels/pack.cc \
../Middlewares/TFLM/micro/kernels/pack_test.cc \
../Middlewares/TFLM/micro/kernels/pad.cc \
../Middlewares/TFLM/micro/kernels/pad_common.cc \
../Middlewares/TFLM/micro/kernels/pad_test.cc \
../Middlewares/TFLM/micro/kernels/pooling.cc \
../Middlewares/TFLM/micro/kernels/pooling_common.cc \
../Middlewares/TFLM/micro/kernels/pooling_test.cc \
../Middlewares/TFLM/micro/kernels/prelu.cc \
../Middlewares/TFLM/micro/kernels/prelu_common.cc \
../Middlewares/TFLM/micro/kernels/prelu_test.cc \
../Middlewares/TFLM/micro/kernels/quantization_util_test.cc \
../Middlewares/TFLM/micro/kernels/quantize.cc \
../Middlewares/TFLM/micro/kernels/quantize_common.cc \
../Middlewares/TFLM/micro/kernels/quantize_test.cc \
../Middlewares/TFLM/micro/kernels/read_variable.cc \
../Middlewares/TFLM/micro/kernels/reduce.cc \
../Middlewares/TFLM/micro/kernels/reduce_common.cc \
../Middlewares/TFLM/micro/kernels/reduce_test.cc \
../Middlewares/TFLM/micro/kernels/reshape.cc \
../Middlewares/TFLM/micro/kernels/reshape_common.cc \
../Middlewares/TFLM/micro/kernels/reshape_test.cc \
../Middlewares/TFLM/micro/kernels/resize_bilinear.cc \
../Middlewares/TFLM/micro/kernels/resize_bilinear_test.cc \
../Middlewares/TFLM/micro/kernels/resize_nearest_neighbor.cc \
../Middlewares/TFLM/micro/kernels/resize_nearest_neighbor_test.cc \
../Middlewares/TFLM/micro/kernels/round.cc \
../Middlewares/TFLM/micro/kernels/round_test.cc \
../Middlewares/TFLM/micro/kernels/select.cc \
../Middlewares/TFLM/micro/kernels/select_test.cc \
../Middlewares/TFLM/micro/kernels/shape.cc \
../Middlewares/TFLM/micro/kernels/shape_test.cc \
../Middlewares/TFLM/micro/kernels/slice.cc \
../Middlewares/TFLM/micro/kernels/slice_test.cc \
../Middlewares/TFLM/micro/kernels/softmax.cc \
../Middlewares/TFLM/micro/kernels/softmax_common.cc \
../Middlewares/TFLM/micro/kernels/softmax_test.cc \
../Middlewares/TFLM/micro/kernels/space_to_batch_nd.cc \
../Middlewares/TFLM/micro/kernels/space_to_batch_nd_test.cc \
../Middlewares/TFLM/micro/kernels/space_to_depth.cc \
../Middlewares/TFLM/micro/kernels/space_to_depth_test.cc \
../Middlewares/TFLM/micro/kernels/split.cc \
../Middlewares/TFLM/micro/kernels/split_test.cc \
../Middlewares/TFLM/micro/kernels/split_v.cc \
../Middlewares/TFLM/micro/kernels/split_v_test.cc \
../Middlewares/TFLM/micro/kernels/squared_difference.cc \
../Middlewares/TFLM/micro/kernels/squared_difference_test.cc \
../Middlewares/TFLM/micro/kernels/squeeze.cc \
../Middlewares/TFLM/micro/kernels/squeeze_test.cc \
../Middlewares/TFLM/micro/kernels/strided_slice.cc \
../Middlewares/TFLM/micro/kernels/strided_slice_common.cc \
../Middlewares/TFLM/micro/kernels/strided_slice_test.cc \
../Middlewares/TFLM/micro/kernels/sub.cc \
../Middlewares/TFLM/micro/kernels/sub_common.cc \
../Middlewares/TFLM/micro/kernels/sub_test.cc \
../Middlewares/TFLM/micro/kernels/svdf.cc \
../Middlewares/TFLM/micro/kernels/svdf_common.cc \
../Middlewares/TFLM/micro/kernels/svdf_test.cc \
../Middlewares/TFLM/micro/kernels/tanh.cc \
../Middlewares/TFLM/micro/kernels/tanh_test.cc \
../Middlewares/TFLM/micro/kernels/transpose.cc \
../Middlewares/TFLM/micro/kernels/transpose_common.cc \
../Middlewares/TFLM/micro/kernels/transpose_conv.cc \
../Middlewares/TFLM/micro/kernels/transpose_conv_test.cc \
../Middlewares/TFLM/micro/kernels/transpose_test.cc \
../Middlewares/TFLM/micro/kernels/unidirectional_sequence_lstm.cc \
../Middlewares/TFLM/micro/kernels/unidirectional_sequence_lstm_test.cc \
../Middlewares/TFLM/micro/kernels/unpack.cc \
../Middlewares/TFLM/micro/kernels/unpack_test.cc \
../Middlewares/TFLM/micro/kernels/var_handle.cc \
../Middlewares/TFLM/micro/kernels/while.cc \
../Middlewares/TFLM/micro/kernels/while_test.cc \
../Middlewares/TFLM/micro/kernels/zeros_like.cc \
../Middlewares/TFLM/micro/kernels/zeros_like_test.cc 

CC_DEPS += \
./Middlewares/TFLM/micro/kernels/activations.d \
./Middlewares/TFLM/micro/kernels/activations_common.d \
./Middlewares/TFLM/micro/kernels/activations_test.d \
./Middlewares/TFLM/micro/kernels/add.d \
./Middlewares/TFLM/micro/kernels/add_common.d \
./Middlewares/TFLM/micro/kernels/add_n.d \
./Middlewares/TFLM/micro/kernels/add_n_test.d \
./Middlewares/TFLM/micro/kernels/add_test.d \
./Middlewares/TFLM/micro/kernels/arg_min_max.d \
./Middlewares/TFLM/micro/kernels/arg_min_max_test.d \
./Middlewares/TFLM/micro/kernels/assign_variable.d \
./Middlewares/TFLM/micro/kernels/batch_matmul.d \
./Middlewares/TFLM/micro/kernels/batch_matmul_common.d \
./Middlewares/TFLM/micro/kernels/batch_matmul_test.d \
./Middlewares/TFLM/micro/kernels/batch_to_space_nd.d \
./Middlewares/TFLM/micro/kernels/batch_to_space_nd_test.d \
./Middlewares/TFLM/micro/kernels/broadcast_args.d \
./Middlewares/TFLM/micro/kernels/broadcast_args_test.d \
./Middlewares/TFLM/micro/kernels/broadcast_to.d \
./Middlewares/TFLM/micro/kernels/broadcast_to_test.d \
./Middlewares/TFLM/micro/kernels/call_once.d \
./Middlewares/TFLM/micro/kernels/call_once_test.d \
./Middlewares/TFLM/micro/kernels/cast.d \
./Middlewares/TFLM/micro/kernels/cast_test.d \
./Middlewares/TFLM/micro/kernels/ceil.d \
./Middlewares/TFLM/micro/kernels/ceil_test.d \
./Middlewares/TFLM/micro/kernels/circular_buffer.d \
./Middlewares/TFLM/micro/kernels/circular_buffer_common.d \
./Middlewares/TFLM/micro/kernels/circular_buffer_flexbuffers_generated_data.d \
./Middlewares/TFLM/micro/kernels/circular_buffer_test.d \
./Middlewares/TFLM/micro/kernels/comparisons.d \
./Middlewares/TFLM/micro/kernels/comparisons_test.d \
./Middlewares/TFLM/micro/kernels/concatenation.d \
./Middlewares/TFLM/micro/kernels/concatenation_test.d \
./Middlewares/TFLM/micro/kernels/conv.d \
./Middlewares/TFLM/micro/kernels/conv_common.d \
./Middlewares/TFLM/micro/kernels/conv_test.d \
./Middlewares/TFLM/micro/kernels/conv_test_common.d \
./Middlewares/TFLM/micro/kernels/cumsum.d \
./Middlewares/TFLM/micro/kernels/cumsum_test.d \
./Middlewares/TFLM/micro/kernels/decompress.d \
./Middlewares/TFLM/micro/kernels/decompress_common.d \
./Middlewares/TFLM/micro/kernels/decompress_test.d \
./Middlewares/TFLM/micro/kernels/depth_to_space.d \
./Middlewares/TFLM/micro/kernels/depth_to_space_test.d \
./Middlewares/TFLM/micro/kernels/depthwise_conv.d \
./Middlewares/TFLM/micro/kernels/depthwise_conv_common.d \
./Middlewares/TFLM/micro/kernels/depthwise_conv_test.d \
./Middlewares/TFLM/micro/kernels/dequantize.d \
./Middlewares/TFLM/micro/kernels/dequantize_common.d \
./Middlewares/TFLM/micro/kernels/dequantize_test.d \
./Middlewares/TFLM/micro/kernels/detection_postprocess.d \
./Middlewares/TFLM/micro/kernels/detection_postprocess_flexbuffers_generated_data.d \
./Middlewares/TFLM/micro/kernels/detection_postprocess_test.d \
./Middlewares/TFLM/micro/kernels/div.d \
./Middlewares/TFLM/micro/kernels/div_test.d \
./Middlewares/TFLM/micro/kernels/elementwise.d \
./Middlewares/TFLM/micro/kernels/elementwise_test.d \
./Middlewares/TFLM/micro/kernels/elu.d \
./Middlewares/TFLM/micro/kernels/elu_test.d \
./Middlewares/TFLM/micro/kernels/embedding_lookup.d \
./Middlewares/TFLM/micro/kernels/embedding_lookup_test.d \
./Middlewares/TFLM/micro/kernels/ethosu.d \
./Middlewares/TFLM/micro/kernels/exp.d \
./Middlewares/TFLM/micro/kernels/exp_test.d \
./Middlewares/TFLM/micro/kernels/expand_dims.d \
./Middlewares/TFLM/micro/kernels/expand_dims_test.d \
./Middlewares/TFLM/micro/kernels/fill.d \
./Middlewares/TFLM/micro/kernels/fill_test.d \
./Middlewares/TFLM/micro/kernels/floor.d \
./Middlewares/TFLM/micro/kernels/floor_div.d \
./Middlewares/TFLM/micro/kernels/floor_div_test.d \
./Middlewares/TFLM/micro/kernels/floor_mod.d \
./Middlewares/TFLM/micro/kernels/floor_mod_test.d \
./Middlewares/TFLM/micro/kernels/floor_test.d \
./Middlewares/TFLM/micro/kernels/fully_connected.d \
./Middlewares/TFLM/micro/kernels/fully_connected_common.d \
./Middlewares/TFLM/micro/kernels/fully_connected_test.d \
./Middlewares/TFLM/micro/kernels/gather.d \
./Middlewares/TFLM/micro/kernels/gather_nd.d \
./Middlewares/TFLM/micro/kernels/gather_nd_test.d \
./Middlewares/TFLM/micro/kernels/gather_test.d \
./Middlewares/TFLM/micro/kernels/hard_swish.d \
./Middlewares/TFLM/micro/kernels/hard_swish_common.d \
./Middlewares/TFLM/micro/kernels/hard_swish_test.d \
./Middlewares/TFLM/micro/kernels/if.d \
./Middlewares/TFLM/micro/kernels/if_test.d \
./Middlewares/TFLM/micro/kernels/kernel_runner.d \
./Middlewares/TFLM/micro/kernels/kernel_util.d \
./Middlewares/TFLM/micro/kernels/l2_pool_2d.d \
./Middlewares/TFLM/micro/kernels/l2_pool_2d_test.d \
./Middlewares/TFLM/micro/kernels/l2norm.d \
./Middlewares/TFLM/micro/kernels/l2norm_test.d \
./Middlewares/TFLM/micro/kernels/leaky_relu.d \
./Middlewares/TFLM/micro/kernels/leaky_relu_common.d \
./Middlewares/TFLM/micro/kernels/leaky_relu_test.d \
./Middlewares/TFLM/micro/kernels/log_softmax.d \
./Middlewares/TFLM/micro/kernels/log_softmax_test.d \
./Middlewares/TFLM/micro/kernels/logical.d \
./Middlewares/TFLM/micro/kernels/logical_common.d \
./Middlewares/TFLM/micro/kernels/logical_test.d \
./Middlewares/TFLM/micro/kernels/logistic.d \
./Middlewares/TFLM/micro/kernels/logistic_common.d \
./Middlewares/TFLM/micro/kernels/logistic_test.d \
./Middlewares/TFLM/micro/kernels/lstm_eval.d \
./Middlewares/TFLM/micro/kernels/lstm_eval_common.d \
./Middlewares/TFLM/micro/kernels/lstm_eval_test.d \
./Middlewares/TFLM/micro/kernels/maximum_minimum.d \
./Middlewares/TFLM/micro/kernels/maximum_minimum_test.d \
./Middlewares/TFLM/micro/kernels/micro_tensor_utils.d \
./Middlewares/TFLM/micro/kernels/mirror_pad.d \
./Middlewares/TFLM/micro/kernels/mirror_pad_test.d \
./Middlewares/TFLM/micro/kernels/mul.d \
./Middlewares/TFLM/micro/kernels/mul_common.d \
./Middlewares/TFLM/micro/kernels/mul_test.d \
./Middlewares/TFLM/micro/kernels/neg.d \
./Middlewares/TFLM/micro/kernels/neg_test.d \
./Middlewares/TFLM/micro/kernels/pack.d \
./Middlewares/TFLM/micro/kernels/pack_test.d \
./Middlewares/TFLM/micro/kernels/pad.d \
./Middlewares/TFLM/micro/kernels/pad_common.d \
./Middlewares/TFLM/micro/kernels/pad_test.d \
./Middlewares/TFLM/micro/kernels/pooling.d \
./Middlewares/TFLM/micro/kernels/pooling_common.d \
./Middlewares/TFLM/micro/kernels/pooling_test.d \
./Middlewares/TFLM/micro/kernels/prelu.d \
./Middlewares/TFLM/micro/kernels/prelu_common.d \
./Middlewares/TFLM/micro/kernels/prelu_test.d \
./Middlewares/TFLM/micro/kernels/quantization_util_test.d \
./Middlewares/TFLM/micro/kernels/quantize.d \
./Middlewares/TFLM/micro/kernels/quantize_common.d \
./Middlewares/TFLM/micro/kernels/quantize_test.d \
./Middlewares/TFLM/micro/kernels/read_variable.d \
./Middlewares/TFLM/micro/kernels/reduce.d \
./Middlewares/TFLM/micro/kernels/reduce_common.d \
./Middlewares/TFLM/micro/kernels/reduce_test.d \
./Middlewares/TFLM/micro/kernels/reshape.d \
./Middlewares/TFLM/micro/kernels/reshape_common.d \
./Middlewares/TFLM/micro/kernels/reshape_test.d \
./Middlewares/TFLM/micro/kernels/resize_bilinear.d \
./Middlewares/TFLM/micro/kernels/resize_bilinear_test.d \
./Middlewares/TFLM/micro/kernels/resize_nearest_neighbor.d \
./Middlewares/TFLM/micro/kernels/resize_nearest_neighbor_test.d \
./Middlewares/TFLM/micro/kernels/round.d \
./Middlewares/TFLM/micro/kernels/round_test.d \
./Middlewares/TFLM/micro/kernels/select.d \
./Middlewares/TFLM/micro/kernels/select_test.d \
./Middlewares/TFLM/micro/kernels/shape.d \
./Middlewares/TFLM/micro/kernels/shape_test.d \
./Middlewares/TFLM/micro/kernels/slice.d \
./Middlewares/TFLM/micro/kernels/slice_test.d \
./Middlewares/TFLM/micro/kernels/softmax.d \
./Middlewares/TFLM/micro/kernels/softmax_common.d \
./Middlewares/TFLM/micro/kernels/softmax_test.d \
./Middlewares/TFLM/micro/kernels/space_to_batch_nd.d \
./Middlewares/TFLM/micro/kernels/space_to_batch_nd_test.d \
./Middlewares/TFLM/micro/kernels/space_to_depth.d \
./Middlewares/TFLM/micro/kernels/space_to_depth_test.d \
./Middlewares/TFLM/micro/kernels/split.d \
./Middlewares/TFLM/micro/kernels/split_test.d \
./Middlewares/TFLM/micro/kernels/split_v.d \
./Middlewares/TFLM/micro/kernels/split_v_test.d \
./Middlewares/TFLM/micro/kernels/squared_difference.d \
./Middlewares/TFLM/micro/kernels/squared_difference_test.d \
./Middlewares/TFLM/micro/kernels/squeeze.d \
./Middlewares/TFLM/micro/kernels/squeeze_test.d \
./Middlewares/TFLM/micro/kernels/strided_slice.d \
./Middlewares/TFLM/micro/kernels/strided_slice_common.d \
./Middlewares/TFLM/micro/kernels/strided_slice_test.d \
./Middlewares/TFLM/micro/kernels/sub.d \
./Middlewares/TFLM/micro/kernels/sub_common.d \
./Middlewares/TFLM/micro/kernels/sub_test.d \
./Middlewares/TFLM/micro/kernels/svdf.d \
./Middlewares/TFLM/micro/kernels/svdf_common.d \
./Middlewares/TFLM/micro/kernels/svdf_test.d \
./Middlewares/TFLM/micro/kernels/tanh.d \
./Middlewares/TFLM/micro/kernels/tanh_test.d \
./Middlewares/TFLM/micro/kernels/transpose.d \
./Middlewares/TFLM/micro/kernels/transpose_common.d \
./Middlewares/TFLM/micro/kernels/transpose_conv.d \
./Middlewares/TFLM/micro/kernels/transpose_conv_test.d \
./Middlewares/TFLM/micro/kernels/transpose_test.d \
./Middlewares/TFLM/micro/kernels/unidirectional_sequence_lstm.d \
./Middlewares/TFLM/micro/kernels/unidirectional_sequence_lstm_test.d \
./Middlewares/TFLM/micro/kernels/unpack.d \
./Middlewares/TFLM/micro/kernels/unpack_test.d \
./Middlewares/TFLM/micro/kernels/var_handle.d \
./Middlewares/TFLM/micro/kernels/while.d \
./Middlewares/TFLM/micro/kernels/while_test.d \
./Middlewares/TFLM/micro/kernels/zeros_like.d \
./Middlewares/TFLM/micro/kernels/zeros_like_test.d 

OBJS += \
./Middlewares/TFLM/micro/kernels/activations.o \
./Middlewares/TFLM/micro/kernels/activations_common.o \
./Middlewares/TFLM/micro/kernels/activations_test.o \
./Middlewares/TFLM/micro/kernels/add.o \
./Middlewares/TFLM/micro/kernels/add_common.o \
./Middlewares/TFLM/micro/kernels/add_n.o \
./Middlewares/TFLM/micro/kernels/add_n_test.o \
./Middlewares/TFLM/micro/kernels/add_test.o \
./Middlewares/TFLM/micro/kernels/arg_min_max.o \
./Middlewares/TFLM/micro/kernels/arg_min_max_test.o \
./Middlewares/TFLM/micro/kernels/assign_variable.o \
./Middlewares/TFLM/micro/kernels/batch_matmul.o \
./Middlewares/TFLM/micro/kernels/batch_matmul_common.o \
./Middlewares/TFLM/micro/kernels/batch_matmul_test.o \
./Middlewares/TFLM/micro/kernels/batch_to_space_nd.o \
./Middlewares/TFLM/micro/kernels/batch_to_space_nd_test.o \
./Middlewares/TFLM/micro/kernels/broadcast_args.o \
./Middlewares/TFLM/micro/kernels/broadcast_args_test.o \
./Middlewares/TFLM/micro/kernels/broadcast_to.o \
./Middlewares/TFLM/micro/kernels/broadcast_to_test.o \
./Middlewares/TFLM/micro/kernels/call_once.o \
./Middlewares/TFLM/micro/kernels/call_once_test.o \
./Middlewares/TFLM/micro/kernels/cast.o \
./Middlewares/TFLM/micro/kernels/cast_test.o \
./Middlewares/TFLM/micro/kernels/ceil.o \
./Middlewares/TFLM/micro/kernels/ceil_test.o \
./Middlewares/TFLM/micro/kernels/circular_buffer.o \
./Middlewares/TFLM/micro/kernels/circular_buffer_common.o \
./Middlewares/TFLM/micro/kernels/circular_buffer_flexbuffers_generated_data.o \
./Middlewares/TFLM/micro/kernels/circular_buffer_test.o \
./Middlewares/TFLM/micro/kernels/comparisons.o \
./Middlewares/TFLM/micro/kernels/comparisons_test.o \
./Middlewares/TFLM/micro/kernels/concatenation.o \
./Middlewares/TFLM/micro/kernels/concatenation_test.o \
./Middlewares/TFLM/micro/kernels/conv.o \
./Middlewares/TFLM/micro/kernels/conv_common.o \
./Middlewares/TFLM/micro/kernels/conv_test.o \
./Middlewares/TFLM/micro/kernels/conv_test_common.o \
./Middlewares/TFLM/micro/kernels/cumsum.o \
./Middlewares/TFLM/micro/kernels/cumsum_test.o \
./Middlewares/TFLM/micro/kernels/decompress.o \
./Middlewares/TFLM/micro/kernels/decompress_common.o \
./Middlewares/TFLM/micro/kernels/decompress_test.o \
./Middlewares/TFLM/micro/kernels/depth_to_space.o \
./Middlewares/TFLM/micro/kernels/depth_to_space_test.o \
./Middlewares/TFLM/micro/kernels/depthwise_conv.o \
./Middlewares/TFLM/micro/kernels/depthwise_conv_common.o \
./Middlewares/TFLM/micro/kernels/depthwise_conv_test.o \
./Middlewares/TFLM/micro/kernels/dequantize.o \
./Middlewares/TFLM/micro/kernels/dequantize_common.o \
./Middlewares/TFLM/micro/kernels/dequantize_test.o \
./Middlewares/TFLM/micro/kernels/detection_postprocess.o \
./Middlewares/TFLM/micro/kernels/detection_postprocess_flexbuffers_generated_data.o \
./Middlewares/TFLM/micro/kernels/detection_postprocess_test.o \
./Middlewares/TFLM/micro/kernels/div.o \
./Middlewares/TFLM/micro/kernels/div_test.o \
./Middlewares/TFLM/micro/kernels/elementwise.o \
./Middlewares/TFLM/micro/kernels/elementwise_test.o \
./Middlewares/TFLM/micro/kernels/elu.o \
./Middlewares/TFLM/micro/kernels/elu_test.o \
./Middlewares/TFLM/micro/kernels/embedding_lookup.o \
./Middlewares/TFLM/micro/kernels/embedding_lookup_test.o \
./Middlewares/TFLM/micro/kernels/ethosu.o \
./Middlewares/TFLM/micro/kernels/exp.o \
./Middlewares/TFLM/micro/kernels/exp_test.o \
./Middlewares/TFLM/micro/kernels/expand_dims.o \
./Middlewares/TFLM/micro/kernels/expand_dims_test.o \
./Middlewares/TFLM/micro/kernels/fill.o \
./Middlewares/TFLM/micro/kernels/fill_test.o \
./Middlewares/TFLM/micro/kernels/floor.o \
./Middlewares/TFLM/micro/kernels/floor_div.o \
./Middlewares/TFLM/micro/kernels/floor_div_test.o \
./Middlewares/TFLM/micro/kernels/floor_mod.o \
./Middlewares/TFLM/micro/kernels/floor_mod_test.o \
./Middlewares/TFLM/micro/kernels/floor_test.o \
./Middlewares/TFLM/micro/kernels/fully_connected.o \
./Middlewares/TFLM/micro/kernels/fully_connected_common.o \
./Middlewares/TFLM/micro/kernels/fully_connected_test.o \
./Middlewares/TFLM/micro/kernels/gather.o \
./Middlewares/TFLM/micro/kernels/gather_nd.o \
./Middlewares/TFLM/micro/kernels/gather_nd_test.o \
./Middlewares/TFLM/micro/kernels/gather_test.o \
./Middlewares/TFLM/micro/kernels/hard_swish.o \
./Middlewares/TFLM/micro/kernels/hard_swish_common.o \
./Middlewares/TFLM/micro/kernels/hard_swish_test.o \
./Middlewares/TFLM/micro/kernels/if.o \
./Middlewares/TFLM/micro/kernels/if_test.o \
./Middlewares/TFLM/micro/kernels/kernel_runner.o \
./Middlewares/TFLM/micro/kernels/kernel_util.o \
./Middlewares/TFLM/micro/kernels/l2_pool_2d.o \
./Middlewares/TFLM/micro/kernels/l2_pool_2d_test.o \
./Middlewares/TFLM/micro/kernels/l2norm.o \
./Middlewares/TFLM/micro/kernels/l2norm_test.o \
./Middlewares/TFLM/micro/kernels/leaky_relu.o \
./Middlewares/TFLM/micro/kernels/leaky_relu_common.o \
./Middlewares/TFLM/micro/kernels/leaky_relu_test.o \
./Middlewares/TFLM/micro/kernels/log_softmax.o \
./Middlewares/TFLM/micro/kernels/log_softmax_test.o \
./Middlewares/TFLM/micro/kernels/logical.o \
./Middlewares/TFLM/micro/kernels/logical_common.o \
./Middlewares/TFLM/micro/kernels/logical_test.o \
./Middlewares/TFLM/micro/kernels/logistic.o \
./Middlewares/TFLM/micro/kernels/logistic_common.o \
./Middlewares/TFLM/micro/kernels/logistic_test.o \
./Middlewares/TFLM/micro/kernels/lstm_eval.o \
./Middlewares/TFLM/micro/kernels/lstm_eval_common.o \
./Middlewares/TFLM/micro/kernels/lstm_eval_test.o \
./Middlewares/TFLM/micro/kernels/maximum_minimum.o \
./Middlewares/TFLM/micro/kernels/maximum_minimum_test.o \
./Middlewares/TFLM/micro/kernels/micro_tensor_utils.o \
./Middlewares/TFLM/micro/kernels/mirror_pad.o \
./Middlewares/TFLM/micro/kernels/mirror_pad_test.o \
./Middlewares/TFLM/micro/kernels/mul.o \
./Middlewares/TFLM/micro/kernels/mul_common.o \
./Middlewares/TFLM/micro/kernels/mul_test.o \
./Middlewares/TFLM/micro/kernels/neg.o \
./Middlewares/TFLM/micro/kernels/neg_test.o \
./Middlewares/TFLM/micro/kernels/pack.o \
./Middlewares/TFLM/micro/kernels/pack_test.o \
./Middlewares/TFLM/micro/kernels/pad.o \
./Middlewares/TFLM/micro/kernels/pad_common.o \
./Middlewares/TFLM/micro/kernels/pad_test.o \
./Middlewares/TFLM/micro/kernels/pooling.o \
./Middlewares/TFLM/micro/kernels/pooling_common.o \
./Middlewares/TFLM/micro/kernels/pooling_test.o \
./Middlewares/TFLM/micro/kernels/prelu.o \
./Middlewares/TFLM/micro/kernels/prelu_common.o \
./Middlewares/TFLM/micro/kernels/prelu_test.o \
./Middlewares/TFLM/micro/kernels/quantization_util_test.o \
./Middlewares/TFLM/micro/kernels/quantize.o \
./Middlewares/TFLM/micro/kernels/quantize_common.o \
./Middlewares/TFLM/micro/kernels/quantize_test.o \
./Middlewares/TFLM/micro/kernels/read_variable.o \
./Middlewares/TFLM/micro/kernels/reduce.o \
./Middlewares/TFLM/micro/kernels/reduce_common.o \
./Middlewares/TFLM/micro/kernels/reduce_test.o \
./Middlewares/TFLM/micro/kernels/reshape.o \
./Middlewares/TFLM/micro/kernels/reshape_common.o \
./Middlewares/TFLM/micro/kernels/reshape_test.o \
./Middlewares/TFLM/micro/kernels/resize_bilinear.o \
./Middlewares/TFLM/micro/kernels/resize_bilinear_test.o \
./Middlewares/TFLM/micro/kernels/resize_nearest_neighbor.o \
./Middlewares/TFLM/micro/kernels/resize_nearest_neighbor_test.o \
./Middlewares/TFLM/micro/kernels/round.o \
./Middlewares/TFLM/micro/kernels/round_test.o \
./Middlewares/TFLM/micro/kernels/select.o \
./Middlewares/TFLM/micro/kernels/select_test.o \
./Middlewares/TFLM/micro/kernels/shape.o \
./Middlewares/TFLM/micro/kernels/shape_test.o \
./Middlewares/TFLM/micro/kernels/slice.o \
./Middlewares/TFLM/micro/kernels/slice_test.o \
./Middlewares/TFLM/micro/kernels/softmax.o \
./Middlewares/TFLM/micro/kernels/softmax_common.o \
./Middlewares/TFLM/micro/kernels/softmax_test.o \
./Middlewares/TFLM/micro/kernels/space_to_batch_nd.o \
./Middlewares/TFLM/micro/kernels/space_to_batch_nd_test.o \
./Middlewares/TFLM/micro/kernels/space_to_depth.o \
./Middlewares/TFLM/micro/kernels/space_to_depth_test.o \
./Middlewares/TFLM/micro/kernels/split.o \
./Middlewares/TFLM/micro/kernels/split_test.o \
./Middlewares/TFLM/micro/kernels/split_v.o \
./Middlewares/TFLM/micro/kernels/split_v_test.o \
./Middlewares/TFLM/micro/kernels/squared_difference.o \
./Middlewares/TFLM/micro/kernels/squared_difference_test.o \
./Middlewares/TFLM/micro/kernels/squeeze.o \
./Middlewares/TFLM/micro/kernels/squeeze_test.o \
./Middlewares/TFLM/micro/kernels/strided_slice.o \
./Middlewares/TFLM/micro/kernels/strided_slice_common.o \
./Middlewares/TFLM/micro/kernels/strided_slice_test.o \
./Middlewares/TFLM/micro/kernels/sub.o \
./Middlewares/TFLM/micro/kernels/sub_common.o \
./Middlewares/TFLM/micro/kernels/sub_test.o \
./Middlewares/TFLM/micro/kernels/svdf.o \
./Middlewares/TFLM/micro/kernels/svdf_common.o \
./Middlewares/TFLM/micro/kernels/svdf_test.o \
./Middlewares/TFLM/micro/kernels/tanh.o \
./Middlewares/TFLM/micro/kernels/tanh_test.o \
./Middlewares/TFLM/micro/kernels/transpose.o \
./Middlewares/TFLM/micro/kernels/transpose_common.o \
./Middlewares/TFLM/micro/kernels/transpose_conv.o \
./Middlewares/TFLM/micro/kernels/transpose_conv_test.o \
./Middlewares/TFLM/micro/kernels/transpose_test.o \
./Middlewares/TFLM/micro/kernels/unidirectional_sequence_lstm.o \
./Middlewares/TFLM/micro/kernels/unidirectional_sequence_lstm_test.o \
./Middlewares/TFLM/micro/kernels/unpack.o \
./Middlewares/TFLM/micro/kernels/unpack_test.o \
./Middlewares/TFLM/micro/kernels/var_handle.o \
./Middlewares/TFLM/micro/kernels/while.o \
./Middlewares/TFLM/micro/kernels/while_test.o \
./Middlewares/TFLM/micro/kernels/zeros_like.o \
./Middlewares/TFLM/micro/kernels/zeros_like_test.o 


# Each subdirectory must supply rules for building sources it contributes
Middlewares/TFLM/micro/kernels/%.o Middlewares/TFLM/micro/kernels/%.su Middlewares/TFLM/micro/kernels/%.cyclo: ../Middlewares/TFLM/micro/kernels/%.cc Middlewares/TFLM/micro/kernels/subdir.mk
	arm-none-eabi-g++ "$<" -mcpu=cortex-m4 -std=gnu++14 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32F407xx -c -I../USB_HOST/App -I../USB_HOST/Target -I../Core/Inc -I../Drivers/STM32F4xx_HAL_Driver/Inc -I../Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -I../Middlewares/ST/STM32_USB_Host_Library/Core/Inc -I../Middlewares/ST/STM32_USB_Host_Library/Class/CDC/Inc -I../Drivers/CMSIS/Device/ST/STM32F4xx/Include -I../Drivers/CMSIS/Include -I../Middlewares/Third_Party/FreeRTOS/Source/include -I../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2 -I../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F -O0 -ffunction-sections -fdata-sections -fno-exceptions -fno-rtti -fno-use-cxa-atexit -Wall -std=c++14 -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"

clean: clean-Middlewares-2f-TFLM-2f-micro-2f-kernels

clean-Middlewares-2f-TFLM-2f-micro-2f-kernels:
	-$(RM) ./Middlewares/TFLM/micro/kernels/activations.cyclo ./Middlewares/TFLM/micro/kernels/activations.d ./Middlewares/TFLM/micro/kernels/activations.o ./Middlewares/TFLM/micro/kernels/activations.su ./Middlewares/TFLM/micro/kernels/activations_common.cyclo ./Middlewares/TFLM/micro/kernels/activations_common.d ./Middlewares/TFLM/micro/kernels/activations_common.o ./Middlewares/TFLM/micro/kernels/activations_common.su ./Middlewares/TFLM/micro/kernels/activations_test.cyclo ./Middlewares/TFLM/micro/kernels/activations_test.d ./Middlewares/TFLM/micro/kernels/activations_test.o ./Middlewares/TFLM/micro/kernels/activations_test.su ./Middlewares/TFLM/micro/kernels/add.cyclo ./Middlewares/TFLM/micro/kernels/add.d ./Middlewares/TFLM/micro/kernels/add.o ./Middlewares/TFLM/micro/kernels/add.su ./Middlewares/TFLM/micro/kernels/add_common.cyclo ./Middlewares/TFLM/micro/kernels/add_common.d ./Middlewares/TFLM/micro/kernels/add_common.o ./Middlewares/TFLM/micro/kernels/add_common.su ./Middlewares/TFLM/micro/kernels/add_n.cyclo ./Middlewares/TFLM/micro/kernels/add_n.d ./Middlewares/TFLM/micro/kernels/add_n.o ./Middlewares/TFLM/micro/kernels/add_n.su ./Middlewares/TFLM/micro/kernels/add_n_test.cyclo ./Middlewares/TFLM/micro/kernels/add_n_test.d ./Middlewares/TFLM/micro/kernels/add_n_test.o ./Middlewares/TFLM/micro/kernels/add_n_test.su ./Middlewares/TFLM/micro/kernels/add_test.cyclo ./Middlewares/TFLM/micro/kernels/add_test.d ./Middlewares/TFLM/micro/kernels/add_test.o ./Middlewares/TFLM/micro/kernels/add_test.su ./Middlewares/TFLM/micro/kernels/arg_min_max.cyclo ./Middlewares/TFLM/micro/kernels/arg_min_max.d ./Middlewares/TFLM/micro/kernels/arg_min_max.o ./Middlewares/TFLM/micro/kernels/arg_min_max.su ./Middlewares/TFLM/micro/kernels/arg_min_max_test.cyclo ./Middlewares/TFLM/micro/kernels/arg_min_max_test.d ./Middlewares/TFLM/micro/kernels/arg_min_max_test.o ./Middlewares/TFLM/micro/kernels/arg_min_max_test.su ./Middlewares/TFLM/micro/kernels/assign_variable.cyclo ./Middlewares/TFLM/micro/kernels/assign_variable.d ./Middlewares/TFLM/micro/kernels/assign_variable.o ./Middlewares/TFLM/micro/kernels/assign_variable.su ./Middlewares/TFLM/micro/kernels/batch_matmul.cyclo ./Middlewares/TFLM/micro/kernels/batch_matmul.d ./Middlewares/TFLM/micro/kernels/batch_matmul.o ./Middlewares/TFLM/micro/kernels/batch_matmul.su ./Middlewares/TFLM/micro/kernels/batch_matmul_common.cyclo ./Middlewares/TFLM/micro/kernels/batch_matmul_common.d ./Middlewares/TFLM/micro/kernels/batch_matmul_common.o ./Middlewares/TFLM/micro/kernels/batch_matmul_common.su ./Middlewares/TFLM/micro/kernels/batch_matmul_test.cyclo ./Middlewares/TFLM/micro/kernels/batch_matmul_test.d ./Middlewares/TFLM/micro/kernels/batch_matmul_test.o ./Middlewares/TFLM/micro/kernels/batch_matmul_test.su ./Middlewares/TFLM/micro/kernels/batch_to_space_nd.cyclo ./Middlewares/TFLM/micro/kernels/batch_to_space_nd.d ./Middlewares/TFLM/micro/kernels/batch_to_space_nd.o ./Middlewares/TFLM/micro/kernels/batch_to_space_nd.su ./Middlewares/TFLM/micro/kernels/batch_to_space_nd_test.cyclo ./Middlewares/TFLM/micro/kernels/batch_to_space_nd_test.d ./Middlewares/TFLM/micro/kernels/batch_to_space_nd_test.o ./Middlewares/TFLM/micro/kernels/batch_to_space_nd_test.su ./Middlewares/TFLM/micro/kernels/broadcast_args.cyclo ./Middlewares/TFLM/micro/kernels/broadcast_args.d ./Middlewares/TFLM/micro/kernels/broadcast_args.o ./Middlewares/TFLM/micro/kernels/broadcast_args.su ./Middlewares/TFLM/micro/kernels/broadcast_args_test.cyclo ./Middlewares/TFLM/micro/kernels/broadcast_args_test.d ./Middlewares/TFLM/micro/kernels/broadcast_args_test.o ./Middlewares/TFLM/micro/kernels/broadcast_args_test.su ./Middlewares/TFLM/micro/kernels/broadcast_to.cyclo ./Middlewares/TFLM/micro/kernels/broadcast_to.d ./Middlewares/TFLM/micro/kernels/broadcast_to.o ./Middlewares/TFLM/micro/kernels/broadcast_to.su ./Middlewares/TFLM/micro/kernels/broadcast_to_test.cyclo ./Middlewares/TFLM/micro/kernels/broadcast_to_test.d ./Middlewares/TFLM/micro/kernels/broadcast_to_test.o ./Middlewares/TFLM/micro/kernels/broadcast_to_test.su ./Middlewares/TFLM/micro/kernels/call_once.cyclo ./Middlewares/TFLM/micro/kernels/call_once.d ./Middlewares/TFLM/micro/kernels/call_once.o ./Middlewares/TFLM/micro/kernels/call_once.su ./Middlewares/TFLM/micro/kernels/call_once_test.cyclo ./Middlewares/TFLM/micro/kernels/call_once_test.d ./Middlewares/TFLM/micro/kernels/call_once_test.o ./Middlewares/TFLM/micro/kernels/call_once_test.su ./Middlewares/TFLM/micro/kernels/cast.cyclo ./Middlewares/TFLM/micro/kernels/cast.d ./Middlewares/TFLM/micro/kernels/cast.o ./Middlewares/TFLM/micro/kernels/cast.su ./Middlewares/TFLM/micro/kernels/cast_test.cyclo ./Middlewares/TFLM/micro/kernels/cast_test.d ./Middlewares/TFLM/micro/kernels/cast_test.o ./Middlewares/TFLM/micro/kernels/cast_test.su ./Middlewares/TFLM/micro/kernels/ceil.cyclo ./Middlewares/TFLM/micro/kernels/ceil.d ./Middlewares/TFLM/micro/kernels/ceil.o ./Middlewares/TFLM/micro/kernels/ceil.su ./Middlewares/TFLM/micro/kernels/ceil_test.cyclo ./Middlewares/TFLM/micro/kernels/ceil_test.d ./Middlewares/TFLM/micro/kernels/ceil_test.o ./Middlewares/TFLM/micro/kernels/ceil_test.su ./Middlewares/TFLM/micro/kernels/circular_buffer.cyclo ./Middlewares/TFLM/micro/kernels/circular_buffer.d ./Middlewares/TFLM/micro/kernels/circular_buffer.o ./Middlewares/TFLM/micro/kernels/circular_buffer.su ./Middlewares/TFLM/micro/kernels/circular_buffer_common.cyclo ./Middlewares/TFLM/micro/kernels/circular_buffer_common.d ./Middlewares/TFLM/micro/kernels/circular_buffer_common.o ./Middlewares/TFLM/micro/kernels/circular_buffer_common.su ./Middlewares/TFLM/micro/kernels/circular_buffer_flexbuffers_generated_data.cyclo ./Middlewares/TFLM/micro/kernels/circular_buffer_flexbuffers_generated_data.d ./Middlewares/TFLM/micro/kernels/circular_buffer_flexbuffers_generated_data.o ./Middlewares/TFLM/micro/kernels/circular_buffer_flexbuffers_generated_data.su ./Middlewares/TFLM/micro/kernels/circular_buffer_test.cyclo
	-$(RM) ./Middlewares/TFLM/micro/kernels/circular_buffer_test.d ./Middlewares/TFLM/micro/kernels/circular_buffer_test.o ./Middlewares/TFLM/micro/kernels/circular_buffer_test.su ./Middlewares/TFLM/micro/kernels/comparisons.cyclo ./Middlewares/TFLM/micro/kernels/comparisons.d ./Middlewares/TFLM/micro/kernels/comparisons.o ./Middlewares/TFLM/micro/kernels/comparisons.su ./Middlewares/TFLM/micro/kernels/comparisons_test.cyclo ./Middlewares/TFLM/micro/kernels/comparisons_test.d ./Middlewares/TFLM/micro/kernels/comparisons_test.o ./Middlewares/TFLM/micro/kernels/comparisons_test.su ./Middlewares/TFLM/micro/kernels/concatenation.cyclo ./Middlewares/TFLM/micro/kernels/concatenation.d ./Middlewares/TFLM/micro/kernels/concatenation.o ./Middlewares/TFLM/micro/kernels/concatenation.su ./Middlewares/TFLM/micro/kernels/concatenation_test.cyclo ./Middlewares/TFLM/micro/kernels/concatenation_test.d ./Middlewares/TFLM/micro/kernels/concatenation_test.o ./Middlewares/TFLM/micro/kernels/concatenation_test.su ./Middlewares/TFLM/micro/kernels/conv.cyclo ./Middlewares/TFLM/micro/kernels/conv.d ./Middlewares/TFLM/micro/kernels/conv.o ./Middlewares/TFLM/micro/kernels/conv.su ./Middlewares/TFLM/micro/kernels/conv_common.cyclo ./Middlewares/TFLM/micro/kernels/conv_common.d ./Middlewares/TFLM/micro/kernels/conv_common.o ./Middlewares/TFLM/micro/kernels/conv_common.su ./Middlewares/TFLM/micro/kernels/conv_test.cyclo ./Middlewares/TFLM/micro/kernels/conv_test.d ./Middlewares/TFLM/micro/kernels/conv_test.o ./Middlewares/TFLM/micro/kernels/conv_test.su ./Middlewares/TFLM/micro/kernels/conv_test_common.cyclo ./Middlewares/TFLM/micro/kernels/conv_test_common.d ./Middlewares/TFLM/micro/kernels/conv_test_common.o ./Middlewares/TFLM/micro/kernels/conv_test_common.su ./Middlewares/TFLM/micro/kernels/cumsum.cyclo ./Middlewares/TFLM/micro/kernels/cumsum.d ./Middlewares/TFLM/micro/kernels/cumsum.o ./Middlewares/TFLM/micro/kernels/cumsum.su ./Middlewares/TFLM/micro/kernels/cumsum_test.cyclo ./Middlewares/TFLM/micro/kernels/cumsum_test.d ./Middlewares/TFLM/micro/kernels/cumsum_test.o ./Middlewares/TFLM/micro/kernels/cumsum_test.su ./Middlewares/TFLM/micro/kernels/decompress.cyclo ./Middlewares/TFLM/micro/kernels/decompress.d ./Middlewares/TFLM/micro/kernels/decompress.o ./Middlewares/TFLM/micro/kernels/decompress.su ./Middlewares/TFLM/micro/kernels/decompress_common.cyclo ./Middlewares/TFLM/micro/kernels/decompress_common.d ./Middlewares/TFLM/micro/kernels/decompress_common.o ./Middlewares/TFLM/micro/kernels/decompress_common.su ./Middlewares/TFLM/micro/kernels/decompress_test.cyclo ./Middlewares/TFLM/micro/kernels/decompress_test.d ./Middlewares/TFLM/micro/kernels/decompress_test.o ./Middlewares/TFLM/micro/kernels/decompress_test.su ./Middlewares/TFLM/micro/kernels/depth_to_space.cyclo ./Middlewares/TFLM/micro/kernels/depth_to_space.d ./Middlewares/TFLM/micro/kernels/depth_to_space.o ./Middlewares/TFLM/micro/kernels/depth_to_space.su ./Middlewares/TFLM/micro/kernels/depth_to_space_test.cyclo ./Middlewares/TFLM/micro/kernels/depth_to_space_test.d ./Middlewares/TFLM/micro/kernels/depth_to_space_test.o ./Middlewares/TFLM/micro/kernels/depth_to_space_test.su ./Middlewares/TFLM/micro/kernels/depthwise_conv.cyclo ./Middlewares/TFLM/micro/kernels/depthwise_conv.d ./Middlewares/TFLM/micro/kernels/depthwise_conv.o ./Middlewares/TFLM/micro/kernels/depthwise_conv.su ./Middlewares/TFLM/micro/kernels/depthwise_conv_common.cyclo ./Middlewares/TFLM/micro/kernels/depthwise_conv_common.d ./Middlewares/TFLM/micro/kernels/depthwise_conv_common.o ./Middlewares/TFLM/micro/kernels/depthwise_conv_common.su ./Middlewares/TFLM/micro/kernels/depthwise_conv_test.cyclo ./Middlewares/TFLM/micro/kernels/depthwise_conv_test.d ./Middlewares/TFLM/micro/kernels/depthwise_conv_test.o ./Middlewares/TFLM/micro/kernels/depthwise_conv_test.su ./Middlewares/TFLM/micro/kernels/dequantize.cyclo ./Middlewares/TFLM/micro/kernels/dequantize.d ./Middlewares/TFLM/micro/kernels/dequantize.o ./Middlewares/TFLM/micro/kernels/dequantize.su ./Middlewares/TFLM/micro/kernels/dequantize_common.cyclo ./Middlewares/TFLM/micro/kernels/dequantize_common.d ./Middlewares/TFLM/micro/kernels/dequantize_common.o ./Middlewares/TFLM/micro/kernels/dequantize_common.su ./Middlewares/TFLM/micro/kernels/dequantize_test.cyclo ./Middlewares/TFLM/micro/kernels/dequantize_test.d ./Middlewares/TFLM/micro/kernels/dequantize_test.o ./Middlewares/TFLM/micro/kernels/dequantize_test.su ./Middlewares/TFLM/micro/kernels/detection_postprocess.cyclo ./Middlewares/TFLM/micro/kernels/detection_postprocess.d ./Middlewares/TFLM/micro/kernels/detection_postprocess.o ./Middlewares/TFLM/micro/kernels/detection_postprocess.su ./Middlewares/TFLM/micro/kernels/detection_postprocess_flexbuffers_generated_data.cyclo ./Middlewares/TFLM/micro/kernels/detection_postprocess_flexbuffers_generated_data.d ./Middlewares/TFLM/micro/kernels/detection_postprocess_flexbuffers_generated_data.o ./Middlewares/TFLM/micro/kernels/detection_postprocess_flexbuffers_generated_data.su ./Middlewares/TFLM/micro/kernels/detection_postprocess_test.cyclo ./Middlewares/TFLM/micro/kernels/detection_postprocess_test.d ./Middlewares/TFLM/micro/kernels/detection_postprocess_test.o ./Middlewares/TFLM/micro/kernels/detection_postprocess_test.su ./Middlewares/TFLM/micro/kernels/div.cyclo ./Middlewares/TFLM/micro/kernels/div.d ./Middlewares/TFLM/micro/kernels/div.o ./Middlewares/TFLM/micro/kernels/div.su ./Middlewares/TFLM/micro/kernels/div_test.cyclo ./Middlewares/TFLM/micro/kernels/div_test.d ./Middlewares/TFLM/micro/kernels/div_test.o ./Middlewares/TFLM/micro/kernels/div_test.su ./Middlewares/TFLM/micro/kernels/elementwise.cyclo ./Middlewares/TFLM/micro/kernels/elementwise.d ./Middlewares/TFLM/micro/kernels/elementwise.o ./Middlewares/TFLM/micro/kernels/elementwise.su ./Middlewares/TFLM/micro/kernels/elementwise_test.cyclo ./Middlewares/TFLM/micro/kernels/elementwise_test.d ./Middlewares/TFLM/micro/kernels/elementwise_test.o
	-$(RM) ./Middlewares/TFLM/micro/kernels/elementwise_test.su ./Middlewares/TFLM/micro/kernels/elu.cyclo ./Middlewares/TFLM/micro/kernels/elu.d ./Middlewares/TFLM/micro/kernels/elu.o ./Middlewares/TFLM/micro/kernels/elu.su ./Middlewares/TFLM/micro/kernels/elu_test.cyclo ./Middlewares/TFLM/micro/kernels/elu_test.d ./Middlewares/TFLM/micro/kernels/elu_test.o ./Middlewares/TFLM/micro/kernels/elu_test.su ./Middlewares/TFLM/micro/kernels/embedding_lookup.cyclo ./Middlewares/TFLM/micro/kernels/embedding_lookup.d ./Middlewares/TFLM/micro/kernels/embedding_lookup.o ./Middlewares/TFLM/micro/kernels/embedding_lookup.su ./Middlewares/TFLM/micro/kernels/embedding_lookup_test.cyclo ./Middlewares/TFLM/micro/kernels/embedding_lookup_test.d ./Middlewares/TFLM/micro/kernels/embedding_lookup_test.o ./Middlewares/TFLM/micro/kernels/embedding_lookup_test.su ./Middlewares/TFLM/micro/kernels/ethosu.cyclo ./Middlewares/TFLM/micro/kernels/ethosu.d ./Middlewares/TFLM/micro/kernels/ethosu.o ./Middlewares/TFLM/micro/kernels/ethosu.su ./Middlewares/TFLM/micro/kernels/exp.cyclo ./Middlewares/TFLM/micro/kernels/exp.d ./Middlewares/TFLM/micro/kernels/exp.o ./Middlewares/TFLM/micro/kernels/exp.su ./Middlewares/TFLM/micro/kernels/exp_test.cyclo ./Middlewares/TFLM/micro/kernels/exp_test.d ./Middlewares/TFLM/micro/kernels/exp_test.o ./Middlewares/TFLM/micro/kernels/exp_test.su ./Middlewares/TFLM/micro/kernels/expand_dims.cyclo ./Middlewares/TFLM/micro/kernels/expand_dims.d ./Middlewares/TFLM/micro/kernels/expand_dims.o ./Middlewares/TFLM/micro/kernels/expand_dims.su ./Middlewares/TFLM/micro/kernels/expand_dims_test.cyclo ./Middlewares/TFLM/micro/kernels/expand_dims_test.d ./Middlewares/TFLM/micro/kernels/expand_dims_test.o ./Middlewares/TFLM/micro/kernels/expand_dims_test.su ./Middlewares/TFLM/micro/kernels/fill.cyclo ./Middlewares/TFLM/micro/kernels/fill.d ./Middlewares/TFLM/micro/kernels/fill.o ./Middlewares/TFLM/micro/kernels/fill.su ./Middlewares/TFLM/micro/kernels/fill_test.cyclo ./Middlewares/TFLM/micro/kernels/fill_test.d ./Middlewares/TFLM/micro/kernels/fill_test.o ./Middlewares/TFLM/micro/kernels/fill_test.su ./Middlewares/TFLM/micro/kernels/floor.cyclo ./Middlewares/TFLM/micro/kernels/floor.d ./Middlewares/TFLM/micro/kernels/floor.o ./Middlewares/TFLM/micro/kernels/floor.su ./Middlewares/TFLM/micro/kernels/floor_div.cyclo ./Middlewares/TFLM/micro/kernels/floor_div.d ./Middlewares/TFLM/micro/kernels/floor_div.o ./Middlewares/TFLM/micro/kernels/floor_div.su ./Middlewares/TFLM/micro/kernels/floor_div_test.cyclo ./Middlewares/TFLM/micro/kernels/floor_div_test.d ./Middlewares/TFLM/micro/kernels/floor_div_test.o ./Middlewares/TFLM/micro/kernels/floor_div_test.su ./Middlewares/TFLM/micro/kernels/floor_mod.cyclo ./Middlewares/TFLM/micro/kernels/floor_mod.d ./Middlewares/TFLM/micro/kernels/floor_mod.o ./Middlewares/TFLM/micro/kernels/floor_mod.su ./Middlewares/TFLM/micro/kernels/floor_mod_test.cyclo ./Middlewares/TFLM/micro/kernels/floor_mod_test.d ./Middlewares/TFLM/micro/kernels/floor_mod_test.o ./Middlewares/TFLM/micro/kernels/floor_mod_test.su ./Middlewares/TFLM/micro/kernels/floor_test.cyclo ./Middlewares/TFLM/micro/kernels/floor_test.d ./Middlewares/TFLM/micro/kernels/floor_test.o ./Middlewares/TFLM/micro/kernels/floor_test.su ./Middlewares/TFLM/micro/kernels/fully_connected.cyclo ./Middlewares/TFLM/micro/kernels/fully_connected.d ./Middlewares/TFLM/micro/kernels/fully_connected.o ./Middlewares/TFLM/micro/kernels/fully_connected.su ./Middlewares/TFLM/micro/kernels/fully_connected_common.cyclo ./Middlewares/TFLM/micro/kernels/fully_connected_common.d ./Middlewares/TFLM/micro/kernels/fully_connected_common.o ./Middlewares/TFLM/micro/kernels/fully_connected_common.su ./Middlewares/TFLM/micro/kernels/fully_connected_test.cyclo ./Middlewares/TFLM/micro/kernels/fully_connected_test.d ./Middlewares/TFLM/micro/kernels/fully_connected_test.o ./Middlewares/TFLM/micro/kernels/fully_connected_test.su ./Middlewares/TFLM/micro/kernels/gather.cyclo ./Middlewares/TFLM/micro/kernels/gather.d ./Middlewares/TFLM/micro/kernels/gather.o ./Middlewares/TFLM/micro/kernels/gather.su ./Middlewares/TFLM/micro/kernels/gather_nd.cyclo ./Middlewares/TFLM/micro/kernels/gather_nd.d ./Middlewares/TFLM/micro/kernels/gather_nd.o ./Middlewares/TFLM/micro/kernels/gather_nd.su ./Middlewares/TFLM/micro/kernels/gather_nd_test.cyclo ./Middlewares/TFLM/micro/kernels/gather_nd_test.d ./Middlewares/TFLM/micro/kernels/gather_nd_test.o ./Middlewares/TFLM/micro/kernels/gather_nd_test.su ./Middlewares/TFLM/micro/kernels/gather_test.cyclo ./Middlewares/TFLM/micro/kernels/gather_test.d ./Middlewares/TFLM/micro/kernels/gather_test.o ./Middlewares/TFLM/micro/kernels/gather_test.su ./Middlewares/TFLM/micro/kernels/hard_swish.cyclo ./Middlewares/TFLM/micro/kernels/hard_swish.d ./Middlewares/TFLM/micro/kernels/hard_swish.o ./Middlewares/TFLM/micro/kernels/hard_swish.su ./Middlewares/TFLM/micro/kernels/hard_swish_common.cyclo ./Middlewares/TFLM/micro/kernels/hard_swish_common.d ./Middlewares/TFLM/micro/kernels/hard_swish_common.o ./Middlewares/TFLM/micro/kernels/hard_swish_common.su ./Middlewares/TFLM/micro/kernels/hard_swish_test.cyclo ./Middlewares/TFLM/micro/kernels/hard_swish_test.d ./Middlewares/TFLM/micro/kernels/hard_swish_test.o ./Middlewares/TFLM/micro/kernels/hard_swish_test.su ./Middlewares/TFLM/micro/kernels/if.cyclo ./Middlewares/TFLM/micro/kernels/if.d ./Middlewares/TFLM/micro/kernels/if.o ./Middlewares/TFLM/micro/kernels/if.su ./Middlewares/TFLM/micro/kernels/if_test.cyclo ./Middlewares/TFLM/micro/kernels/if_test.d ./Middlewares/TFLM/micro/kernels/if_test.o ./Middlewares/TFLM/micro/kernels/if_test.su ./Middlewares/TFLM/micro/kernels/kernel_runner.cyclo ./Middlewares/TFLM/micro/kernels/kernel_runner.d ./Middlewares/TFLM/micro/kernels/kernel_runner.o ./Middlewares/TFLM/micro/kernels/kernel_runner.su ./Middlewares/TFLM/micro/kernels/kernel_util.cyclo ./Middlewares/TFLM/micro/kernels/kernel_util.d ./Middlewares/TFLM/micro/kernels/kernel_util.o
	-$(RM) ./Middlewares/TFLM/micro/kernels/kernel_util.su ./Middlewares/TFLM/micro/kernels/l2_pool_2d.cyclo ./Middlewares/TFLM/micro/kernels/l2_pool_2d.d ./Middlewares/TFLM/micro/kernels/l2_pool_2d.o ./Middlewares/TFLM/micro/kernels/l2_pool_2d.su ./Middlewares/TFLM/micro/kernels/l2_pool_2d_test.cyclo ./Middlewares/TFLM/micro/kernels/l2_pool_2d_test.d ./Middlewares/TFLM/micro/kernels/l2_pool_2d_test.o ./Middlewares/TFLM/micro/kernels/l2_pool_2d_test.su ./Middlewares/TFLM/micro/kernels/l2norm.cyclo ./Middlewares/TFLM/micro/kernels/l2norm.d ./Middlewares/TFLM/micro/kernels/l2norm.o ./Middlewares/TFLM/micro/kernels/l2norm.su ./Middlewares/TFLM/micro/kernels/l2norm_test.cyclo ./Middlewares/TFLM/micro/kernels/l2norm_test.d ./Middlewares/TFLM/micro/kernels/l2norm_test.o ./Middlewares/TFLM/micro/kernels/l2norm_test.su ./Middlewares/TFLM/micro/kernels/leaky_relu.cyclo ./Middlewares/TFLM/micro/kernels/leaky_relu.d ./Middlewares/TFLM/micro/kernels/leaky_relu.o ./Middlewares/TFLM/micro/kernels/leaky_relu.su ./Middlewares/TFLM/micro/kernels/leaky_relu_common.cyclo ./Middlewares/TFLM/micro/kernels/leaky_relu_common.d ./Middlewares/TFLM/micro/kernels/leaky_relu_common.o ./Middlewares/TFLM/micro/kernels/leaky_relu_common.su ./Middlewares/TFLM/micro/kernels/leaky_relu_test.cyclo ./Middlewares/TFLM/micro/kernels/leaky_relu_test.d ./Middlewares/TFLM/micro/kernels/leaky_relu_test.o ./Middlewares/TFLM/micro/kernels/leaky_relu_test.su ./Middlewares/TFLM/micro/kernels/log_softmax.cyclo ./Middlewares/TFLM/micro/kernels/log_softmax.d ./Middlewares/TFLM/micro/kernels/log_softmax.o ./Middlewares/TFLM/micro/kernels/log_softmax.su ./Middlewares/TFLM/micro/kernels/log_softmax_test.cyclo ./Middlewares/TFLM/micro/kernels/log_softmax_test.d ./Middlewares/TFLM/micro/kernels/log_softmax_test.o ./Middlewares/TFLM/micro/kernels/log_softmax_test.su ./Middlewares/TFLM/micro/kernels/logical.cyclo ./Middlewares/TFLM/micro/kernels/logical.d ./Middlewares/TFLM/micro/kernels/logical.o ./Middlewares/TFLM/micro/kernels/logical.su ./Middlewares/TFLM/micro/kernels/logical_common.cyclo ./Middlewares/TFLM/micro/kernels/logical_common.d ./Middlewares/TFLM/micro/kernels/logical_common.o ./Middlewares/TFLM/micro/kernels/logical_common.su ./Middlewares/TFLM/micro/kernels/logical_test.cyclo ./Middlewares/TFLM/micro/kernels/logical_test.d ./Middlewares/TFLM/micro/kernels/logical_test.o ./Middlewares/TFLM/micro/kernels/logical_test.su ./Middlewares/TFLM/micro/kernels/logistic.cyclo ./Middlewares/TFLM/micro/kernels/logistic.d ./Middlewares/TFLM/micro/kernels/logistic.o ./Middlewares/TFLM/micro/kernels/logistic.su ./Middlewares/TFLM/micro/kernels/logistic_common.cyclo ./Middlewares/TFLM/micro/kernels/logistic_common.d ./Middlewares/TFLM/micro/kernels/logistic_common.o ./Middlewares/TFLM/micro/kernels/logistic_common.su ./Middlewares/TFLM/micro/kernels/logistic_test.cyclo ./Middlewares/TFLM/micro/kernels/logistic_test.d ./Middlewares/TFLM/micro/kernels/logistic_test.o ./Middlewares/TFLM/micro/kernels/logistic_test.su ./Middlewares/TFLM/micro/kernels/lstm_eval.cyclo ./Middlewares/TFLM/micro/kernels/lstm_eval.d ./Middlewares/TFLM/micro/kernels/lstm_eval.o ./Middlewares/TFLM/micro/kernels/lstm_eval.su ./Middlewares/TFLM/micro/kernels/lstm_eval_common.cyclo ./Middlewares/TFLM/micro/kernels/lstm_eval_common.d ./Middlewares/TFLM/micro/kernels/lstm_eval_common.o ./Middlewares/TFLM/micro/kernels/lstm_eval_common.su ./Middlewares/TFLM/micro/kernels/lstm_eval_test.cyclo ./Middlewares/TFLM/micro/kernels/lstm_eval_test.d ./Middlewares/TFLM/micro/kernels/lstm_eval_test.o ./Middlewares/TFLM/micro/kernels/lstm_eval_test.su ./Middlewares/TFLM/micro/kernels/maximum_minimum.cyclo ./Middlewares/TFLM/micro/kernels/maximum_minimum.d ./Middlewares/TFLM/micro/kernels/maximum_minimum.o ./Middlewares/TFLM/micro/kernels/maximum_minimum.su ./Middlewares/TFLM/micro/kernels/maximum_minimum_test.cyclo ./Middlewares/TFLM/micro/kernels/maximum_minimum_test.d ./Middlewares/TFLM/micro/kernels/maximum_minimum_test.o ./Middlewares/TFLM/micro/kernels/maximum_minimum_test.su ./Middlewares/TFLM/micro/kernels/micro_tensor_utils.cyclo ./Middlewares/TFLM/micro/kernels/micro_tensor_utils.d ./Middlewares/TFLM/micro/kernels/micro_tensor_utils.o ./Middlewares/TFLM/micro/kernels/micro_tensor_utils.su ./Middlewares/TFLM/micro/kernels/mirror_pad.cyclo ./Middlewares/TFLM/micro/kernels/mirror_pad.d ./Middlewares/TFLM/micro/kernels/mirror_pad.o ./Middlewares/TFLM/micro/kernels/mirror_pad.su ./Middlewares/TFLM/micro/kernels/mirror_pad_test.cyclo ./Middlewares/TFLM/micro/kernels/mirror_pad_test.d ./Middlewares/TFLM/micro/kernels/mirror_pad_test.o ./Middlewares/TFLM/micro/kernels/mirror_pad_test.su ./Middlewares/TFLM/micro/kernels/mul.cyclo ./Middlewares/TFLM/micro/kernels/mul.d ./Middlewares/TFLM/micro/kernels/mul.o ./Middlewares/TFLM/micro/kernels/mul.su ./Middlewares/TFLM/micro/kernels/mul_common.cyclo ./Middlewares/TFLM/micro/kernels/mul_common.d ./Middlewares/TFLM/micro/kernels/mul_common.o ./Middlewares/TFLM/micro/kernels/mul_common.su ./Middlewares/TFLM/micro/kernels/mul_test.cyclo ./Middlewares/TFLM/micro/kernels/mul_test.d ./Middlewares/TFLM/micro/kernels/mul_test.o ./Middlewares/TFLM/micro/kernels/mul_test.su ./Middlewares/TFLM/micro/kernels/neg.cyclo ./Middlewares/TFLM/micro/kernels/neg.d ./Middlewares/TFLM/micro/kernels/neg.o ./Middlewares/TFLM/micro/kernels/neg.su ./Middlewares/TFLM/micro/kernels/neg_test.cyclo ./Middlewares/TFLM/micro/kernels/neg_test.d ./Middlewares/TFLM/micro/kernels/neg_test.o ./Middlewares/TFLM/micro/kernels/neg_test.su ./Middlewares/TFLM/micro/kernels/pack.cyclo ./Middlewares/TFLM/micro/kernels/pack.d ./Middlewares/TFLM/micro/kernels/pack.o ./Middlewares/TFLM/micro/kernels/pack.su ./Middlewares/TFLM/micro/kernels/pack_test.cyclo ./Middlewares/TFLM/micro/kernels/pack_test.d ./Middlewares/TFLM/micro/kernels/pack_test.o ./Middlewares/TFLM/micro/kernels/pack_test.su ./Middlewares/TFLM/micro/kernels/pad.cyclo ./Middlewares/TFLM/micro/kernels/pad.d
	-$(RM) ./Middlewares/TFLM/micro/kernels/pad.o ./Middlewares/TFLM/micro/kernels/pad.su ./Middlewares/TFLM/micro/kernels/pad_common.cyclo ./Middlewares/TFLM/micro/kernels/pad_common.d ./Middlewares/TFLM/micro/kernels/pad_common.o ./Middlewares/TFLM/micro/kernels/pad_common.su ./Middlewares/TFLM/micro/kernels/pad_test.cyclo ./Middlewares/TFLM/micro/kernels/pad_test.d ./Middlewares/TFLM/micro/kernels/pad_test.o ./Middlewares/TFLM/micro/kernels/pad_test.su ./Middlewares/TFLM/micro/kernels/pooling.cyclo ./Middlewares/TFLM/micro/kernels/pooling.d ./Middlewares/TFLM/micro/kernels/pooling.o ./Middlewares/TFLM/micro/kernels/pooling.su ./Middlewares/TFLM/micro/kernels/pooling_common.cyclo ./Middlewares/TFLM/micro/kernels/pooling_common.d ./Middlewares/TFLM/micro/kernels/pooling_common.o ./Middlewares/TFLM/micro/kernels/pooling_common.su ./Middlewares/TFLM/micro/kernels/pooling_test.cyclo ./Middlewares/TFLM/micro/kernels/pooling_test.d ./Middlewares/TFLM/micro/kernels/pooling_test.o ./Middlewares/TFLM/micro/kernels/pooling_test.su ./Middlewares/TFLM/micro/kernels/prelu.cyclo ./Middlewares/TFLM/micro/kernels/prelu.d ./Middlewares/TFLM/micro/kernels/prelu.o ./Middlewares/TFLM/micro/kernels/prelu.su ./Middlewares/TFLM/micro/kernels/prelu_common.cyclo ./Middlewares/TFLM/micro/kernels/prelu_common.d ./Middlewares/TFLM/micro/kernels/prelu_common.o ./Middlewares/TFLM/micro/kernels/prelu_common.su ./Middlewares/TFLM/micro/kernels/prelu_test.cyclo ./Middlewares/TFLM/micro/kernels/prelu_test.d ./Middlewares/TFLM/micro/kernels/prelu_test.o ./Middlewares/TFLM/micro/kernels/prelu_test.su ./Middlewares/TFLM/micro/kernels/quantization_util_test.cyclo ./Middlewares/TFLM/micro/kernels/quantization_util_test.d ./Middlewares/TFLM/micro/kernels/quantization_util_test.o ./Middlewares/TFLM/micro/kernels/quantization_util_test.su ./Middlewares/TFLM/micro/kernels/quantize.cyclo ./Middlewares/TFLM/micro/kernels/quantize.d ./Middlewares/TFLM/micro/kernels/quantize.o ./Middlewares/TFLM/micro/kernels/quantize.su ./Middlewares/TFLM/micro/kernels/quantize_common.cyclo ./Middlewares/TFLM/micro/kernels/quantize_common.d ./Middlewares/TFLM/micro/kernels/quantize_common.o ./Middlewares/TFLM/micro/kernels/quantize_common.su ./Middlewares/TFLM/micro/kernels/quantize_test.cyclo ./Middlewares/TFLM/micro/kernels/quantize_test.d ./Middlewares/TFLM/micro/kernels/quantize_test.o ./Middlewares/TFLM/micro/kernels/quantize_test.su ./Middlewares/TFLM/micro/kernels/read_variable.cyclo ./Middlewares/TFLM/micro/kernels/read_variable.d ./Middlewares/TFLM/micro/kernels/read_variable.o ./Middlewares/TFLM/micro/kernels/read_variable.su ./Middlewares/TFLM/micro/kernels/reduce.cyclo ./Middlewares/TFLM/micro/kernels/reduce.d ./Middlewares/TFLM/micro/kernels/reduce.o ./Middlewares/TFLM/micro/kernels/reduce.su ./Middlewares/TFLM/micro/kernels/reduce_common.cyclo ./Middlewares/TFLM/micro/kernels/reduce_common.d ./Middlewares/TFLM/micro/kernels/reduce_common.o ./Middlewares/TFLM/micro/kernels/reduce_common.su ./Middlewares/TFLM/micro/kernels/reduce_test.cyclo ./Middlewares/TFLM/micro/kernels/reduce_test.d ./Middlewares/TFLM/micro/kernels/reduce_test.o ./Middlewares/TFLM/micro/kernels/reduce_test.su ./Middlewares/TFLM/micro/kernels/reshape.cyclo ./Middlewares/TFLM/micro/kernels/reshape.d ./Middlewares/TFLM/micro/kernels/reshape.o ./Middlewares/TFLM/micro/kernels/reshape.su ./Middlewares/TFLM/micro/kernels/reshape_common.cyclo ./Middlewares/TFLM/micro/kernels/reshape_common.d ./Middlewares/TFLM/micro/kernels/reshape_common.o ./Middlewares/TFLM/micro/kernels/reshape_common.su ./Middlewares/TFLM/micro/kernels/reshape_test.cyclo ./Middlewares/TFLM/micro/kernels/reshape_test.d ./Middlewares/TFLM/micro/kernels/reshape_test.o ./Middlewares/TFLM/micro/kernels/reshape_test.su ./Middlewares/TFLM/micro/kernels/resize_bilinear.cyclo ./Middlewares/TFLM/micro/kernels/resize_bilinear.d ./Middlewares/TFLM/micro/kernels/resize_bilinear.o ./Middlewares/TFLM/micro/kernels/resize_bilinear.su ./Middlewares/TFLM/micro/kernels/resize_bilinear_test.cyclo ./Middlewares/TFLM/micro/kernels/resize_bilinear_test.d ./Middlewares/TFLM/micro/kernels/resize_bilinear_test.o ./Middlewares/TFLM/micro/kernels/resize_bilinear_test.su ./Middlewares/TFLM/micro/kernels/resize_nearest_neighbor.cyclo ./Middlewares/TFLM/micro/kernels/resize_nearest_neighbor.d ./Middlewares/TFLM/micro/kernels/resize_nearest_neighbor.o ./Middlewares/TFLM/micro/kernels/resize_nearest_neighbor.su ./Middlewares/TFLM/micro/kernels/resize_nearest_neighbor_test.cyclo ./Middlewares/TFLM/micro/kernels/resize_nearest_neighbor_test.d ./Middlewares/TFLM/micro/kernels/resize_nearest_neighbor_test.o ./Middlewares/TFLM/micro/kernels/resize_nearest_neighbor_test.su ./Middlewares/TFLM/micro/kernels/round.cyclo ./Middlewares/TFLM/micro/kernels/round.d ./Middlewares/TFLM/micro/kernels/round.o ./Middlewares/TFLM/micro/kernels/round.su ./Middlewares/TFLM/micro/kernels/round_test.cyclo ./Middlewares/TFLM/micro/kernels/round_test.d ./Middlewares/TFLM/micro/kernels/round_test.o ./Middlewares/TFLM/micro/kernels/round_test.su ./Middlewares/TFLM/micro/kernels/select.cyclo ./Middlewares/TFLM/micro/kernels/select.d ./Middlewares/TFLM/micro/kernels/select.o ./Middlewares/TFLM/micro/kernels/select.su ./Middlewares/TFLM/micro/kernels/select_test.cyclo ./Middlewares/TFLM/micro/kernels/select_test.d ./Middlewares/TFLM/micro/kernels/select_test.o ./Middlewares/TFLM/micro/kernels/select_test.su ./Middlewares/TFLM/micro/kernels/shape.cyclo ./Middlewares/TFLM/micro/kernels/shape.d ./Middlewares/TFLM/micro/kernels/shape.o ./Middlewares/TFLM/micro/kernels/shape.su ./Middlewares/TFLM/micro/kernels/shape_test.cyclo ./Middlewares/TFLM/micro/kernels/shape_test.d ./Middlewares/TFLM/micro/kernels/shape_test.o ./Middlewares/TFLM/micro/kernels/shape_test.su ./Middlewares/TFLM/micro/kernels/slice.cyclo ./Middlewares/TFLM/micro/kernels/slice.d ./Middlewares/TFLM/micro/kernels/slice.o ./Middlewares/TFLM/micro/kernels/slice.su
	-$(RM) ./Middlewares/TFLM/micro/kernels/slice_test.cyclo ./Middlewares/TFLM/micro/kernels/slice_test.d ./Middlewares/TFLM/micro/kernels/slice_test.o ./Middlewares/TFLM/micro/kernels/slice_test.su ./Middlewares/TFLM/micro/kernels/softmax.cyclo ./Middlewares/TFLM/micro/kernels/softmax.d ./Middlewares/TFLM/micro/kernels/softmax.o ./Middlewares/TFLM/micro/kernels/softmax.su ./Middlewares/TFLM/micro/kernels/softmax_common.cyclo ./Middlewares/TFLM/micro/kernels/softmax_common.d ./Middlewares/TFLM/micro/kernels/softmax_common.o ./Middlewares/TFLM/micro/kernels/softmax_common.su ./Middlewares/TFLM/micro/kernels/softmax_test.cyclo ./Middlewares/TFLM/micro/kernels/softmax_test.d ./Middlewares/TFLM/micro/kernels/softmax_test.o ./Middlewares/TFLM/micro/kernels/softmax_test.su ./Middlewares/TFLM/micro/kernels/space_to_batch_nd.cyclo ./Middlewares/TFLM/micro/kernels/space_to_batch_nd.d ./Middlewares/TFLM/micro/kernels/space_to_batch_nd.o ./Middlewares/TFLM/micro/kernels/space_to_batch_nd.su ./Middlewares/TFLM/micro/kernels/space_to_batch_nd_test.cyclo ./Middlewares/TFLM/micro/kernels/space_to_batch_nd_test.d ./Middlewares/TFLM/micro/kernels/space_to_batch_nd_test.o ./Middlewares/TFLM/micro/kernels/space_to_batch_nd_test.su ./Middlewares/TFLM/micro/kernels/space_to_depth.cyclo ./Middlewares/TFLM/micro/kernels/space_to_depth.d ./Middlewares/TFLM/micro/kernels/space_to_depth.o ./Middlewares/TFLM/micro/kernels/space_to_depth.su ./Middlewares/TFLM/micro/kernels/space_to_depth_test.cyclo ./Middlewares/TFLM/micro/kernels/space_to_depth_test.d ./Middlewares/TFLM/micro/kernels/space_to_depth_test.o ./Middlewares/TFLM/micro/kernels/space_to_depth_test.su ./Middlewares/TFLM/micro/kernels/split.cyclo ./Middlewares/TFLM/micro/kernels/split.d ./Middlewares/TFLM/micro/kernels/split.o ./Middlewares/TFLM/micro/kernels/split.su ./Middlewares/TFLM/micro/kernels/split_test.cyclo ./Middlewares/TFLM/micro/kernels/split_test.d ./Middlewares/TFLM/micro/kernels/split_test.o ./Middlewares/TFLM/micro/kernels/split_test.su ./Middlewares/TFLM/micro/kernels/split_v.cyclo ./Middlewares/TFLM/micro/kernels/split_v.d ./Middlewares/TFLM/micro/kernels/split_v.o ./Middlewares/TFLM/micro/kernels/split_v.su ./Middlewares/TFLM/micro/kernels/split_v_test.cyclo ./Middlewares/TFLM/micro/kernels/split_v_test.d ./Middlewares/TFLM/micro/kernels/split_v_test.o ./Middlewares/TFLM/micro/kernels/split_v_test.su ./Middlewares/TFLM/micro/kernels/squared_difference.cyclo ./Middlewares/TFLM/micro/kernels/squared_difference.d ./Middlewares/TFLM/micro/kernels/squared_difference.o ./Middlewares/TFLM/micro/kernels/squared_difference.su ./Middlewares/TFLM/micro/kernels/squared_difference_test.cyclo ./Middlewares/TFLM/micro/kernels/squared_difference_test.d ./Middlewares/TFLM/micro/kernels/squared_difference_test.o ./Middlewares/TFLM/micro/kernels/squared_difference_test.su ./Middlewares/TFLM/micro/kernels/squeeze.cyclo ./Middlewares/TFLM/micro/kernels/squeeze.d ./Middlewares/TFLM/micro/kernels/squeeze.o ./Middlewares/TFLM/micro/kernels/squeeze.su ./Middlewares/TFLM/micro/kernels/squeeze_test.cyclo ./Middlewares/TFLM/micro/kernels/squeeze_test.d ./Middlewares/TFLM/micro/kernels/squeeze_test.o ./Middlewares/TFLM/micro/kernels/squeeze_test.su ./Middlewares/TFLM/micro/kernels/strided_slice.cyclo ./Middlewares/TFLM/micro/kernels/strided_slice.d ./Middlewares/TFLM/micro/kernels/strided_slice.o ./Middlewares/TFLM/micro/kernels/strided_slice.su ./Middlewares/TFLM/micro/kernels/strided_slice_common.cyclo ./Middlewares/TFLM/micro/kernels/strided_slice_common.d ./Middlewares/TFLM/micro/kernels/strided_slice_common.o ./Middlewares/TFLM/micro/kernels/strided_slice_common.su ./Middlewares/TFLM/micro/kernels/strided_slice_test.cyclo ./Middlewares/TFLM/micro/kernels/strided_slice_test.d ./Middlewares/TFLM/micro/kernels/strided_slice_test.o ./Middlewares/TFLM/micro/kernels/strided_slice_test.su ./Middlewares/TFLM/micro/kernels/sub.cyclo ./Middlewares/TFLM/micro/kernels/sub.d ./Middlewares/TFLM/micro/kernels/sub.o ./Middlewares/TFLM/micro/kernels/sub.su ./Middlewares/TFLM/micro/kernels/sub_common.cyclo ./Middlewares/TFLM/micro/kernels/sub_common.d ./Middlewares/TFLM/micro/kernels/sub_common.o ./Middlewares/TFLM/micro/kernels/sub_common.su ./Middlewares/TFLM/micro/kernels/sub_test.cyclo ./Middlewares/TFLM/micro/kernels/sub_test.d ./Middlewares/TFLM/micro/kernels/sub_test.o ./Middlewares/TFLM/micro/kernels/sub_test.su ./Middlewares/TFLM/micro/kernels/svdf.cyclo ./Middlewares/TFLM/micro/kernels/svdf.d ./Middlewares/TFLM/micro/kernels/svdf.o ./Middlewares/TFLM/micro/kernels/svdf.su ./Middlewares/TFLM/micro/kernels/svdf_common.cyclo ./Middlewares/TFLM/micro/kernels/svdf_common.d ./Middlewares/TFLM/micro/kernels/svdf_common.o ./Middlewares/TFLM/micro/kernels/svdf_common.su ./Middlewares/TFLM/micro/kernels/svdf_test.cyclo ./Middlewares/TFLM/micro/kernels/svdf_test.d ./Middlewares/TFLM/micro/kernels/svdf_test.o ./Middlewares/TFLM/micro/kernels/svdf_test.su ./Middlewares/TFLM/micro/kernels/tanh.cyclo ./Middlewares/TFLM/micro/kernels/tanh.d ./Middlewares/TFLM/micro/kernels/tanh.o ./Middlewares/TFLM/micro/kernels/tanh.su ./Middlewares/TFLM/micro/kernels/tanh_test.cyclo ./Middlewares/TFLM/micro/kernels/tanh_test.d ./Middlewares/TFLM/micro/kernels/tanh_test.o ./Middlewares/TFLM/micro/kernels/tanh_test.su ./Middlewares/TFLM/micro/kernels/transpose.cyclo ./Middlewares/TFLM/micro/kernels/transpose.d ./Middlewares/TFLM/micro/kernels/transpose.o ./Middlewares/TFLM/micro/kernels/transpose.su ./Middlewares/TFLM/micro/kernels/transpose_common.cyclo ./Middlewares/TFLM/micro/kernels/transpose_common.d ./Middlewares/TFLM/micro/kernels/transpose_common.o ./Middlewares/TFLM/micro/kernels/transpose_common.su ./Middlewares/TFLM/micro/kernels/transpose_conv.cyclo ./Middlewares/TFLM/micro/kernels/transpose_conv.d ./Middlewares/TFLM/micro/kernels/transpose_conv.o ./Middlewares/TFLM/micro/kernels/transpose_conv.su ./Middlewares/TFLM/micro/kernels/transpose_conv_test.cyclo
	-$(RM) ./Middlewares/TFLM/micro/kernels/transpose_conv_test.d ./Middlewares/TFLM/micro/kernels/transpose_conv_test.o ./Middlewares/TFLM/micro/kernels/transpose_conv_test.su ./Middlewares/TFLM/micro/kernels/transpose_test.cyclo ./Middlewares/TFLM/micro/kernels/transpose_test.d ./Middlewares/TFLM/micro/kernels/transpose_test.o ./Middlewares/TFLM/micro/kernels/transpose_test.su ./Middlewares/TFLM/micro/kernels/unidirectional_sequence_lstm.cyclo ./Middlewares/TFLM/micro/kernels/unidirectional_sequence_lstm.d ./Middlewares/TFLM/micro/kernels/unidirectional_sequence_lstm.o ./Middlewares/TFLM/micro/kernels/unidirectional_sequence_lstm.su ./Middlewares/TFLM/micro/kernels/unidirectional_sequence_lstm_test.cyclo ./Middlewares/TFLM/micro/kernels/unidirectional_sequence_lstm_test.d ./Middlewares/TFLM/micro/kernels/unidirectional_sequence_lstm_test.o ./Middlewares/TFLM/micro/kernels/unidirectional_sequence_lstm_test.su ./Middlewares/TFLM/micro/kernels/unpack.cyclo ./Middlewares/TFLM/micro/kernels/unpack.d ./Middlewares/TFLM/micro/kernels/unpack.o ./Middlewares/TFLM/micro/kernels/unpack.su ./Middlewares/TFLM/micro/kernels/unpack_test.cyclo ./Middlewares/TFLM/micro/kernels/unpack_test.d ./Middlewares/TFLM/micro/kernels/unpack_test.o ./Middlewares/TFLM/micro/kernels/unpack_test.su ./Middlewares/TFLM/micro/kernels/var_handle.cyclo ./Middlewares/TFLM/micro/kernels/var_handle.d ./Middlewares/TFLM/micro/kernels/var_handle.o ./Middlewares/TFLM/micro/kernels/var_handle.su ./Middlewares/TFLM/micro/kernels/while.cyclo ./Middlewares/TFLM/micro/kernels/while.d ./Middlewares/TFLM/micro/kernels/while.o ./Middlewares/TFLM/micro/kernels/while.su ./Middlewares/TFLM/micro/kernels/while_test.cyclo ./Middlewares/TFLM/micro/kernels/while_test.d ./Middlewares/TFLM/micro/kernels/while_test.o ./Middlewares/TFLM/micro/kernels/while_test.su ./Middlewares/TFLM/micro/kernels/zeros_like.cyclo ./Middlewares/TFLM/micro/kernels/zeros_like.d ./Middlewares/TFLM/micro/kernels/zeros_like.o ./Middlewares/TFLM/micro/kernels/zeros_like.su ./Middlewares/TFLM/micro/kernels/zeros_like_test.cyclo ./Middlewares/TFLM/micro/kernels/zeros_like_test.d ./Middlewares/TFLM/micro/kernels/zeros_like_test.o ./Middlewares/TFLM/micro/kernels/zeros_like_test.su

.PHONY: clean-Middlewares-2f-TFLM-2f-micro-2f-kernels

